### ISSUE TITLE
[Feature] Add Translation Tool 

### ISSUE THREAD

**Issue by Subhajit-2023-44** [swaraj-das/Collect-your-GamingTools#397] opened 2024-10-14 10:10 UTC
### Description

I want to add a Translation Tool(all language) properly.

@swaraj-das  PA please assign me this task.

![Screenshot 2024-10-14 153911](https://github.com/user-attachments/assets/6371fb6e-9a3e-42cd-a09c-1d55b25eccf3)

### Checklist

- [X] I have checked the existing [issues](https://github.com/swaraj-das/Collect-your-GamingTools/issues).
- [X] I have read the [Code Of Conduct](https://github.com/swaraj-das/Collect-your-GamingTools/blob/main/CODE_OF_CONDUCT.md)
- [X] The changes don't break the code
- [X] Please attach the screenshots and video of the development work once it is done

**Comment by mdfarid01** [comment] 2024-10-14 12:55
Can you assign this to me? I have experience building a multilingual website.

**Comment by Subhajit-2023-44** [comment] 2024-10-14 13:25
> Can you assign this to me? I have experience building a multilingual website.

I sent an assign request first and I also have experience..

**Comment by Subhajit-2023-44** [comment] 2024-10-14 21:26
@swaraj-das @AnitSarkar123

**Comment by AnitSarkar123** [comment] 2024-10-15 08:16
@mdfarid01 @Subhajit-2023-44 first come first serve basis

**Comment by Subhajit-2023-44** [comment] 2024-10-15 08:48
> @mdfarid01 @Subhajit-2023-44 first come first serve basis

@AnitSarkar123 please merge my pull request #413

**Comment by mdfarid01** [comment] 2024-12-09 06:54
the issue is already fixed

**Closed** 2024-12-19 11:40 UTC
Labels: enhancement, gssoc-ext, Level3, hacktoberfest-accepted
